'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dashboard1

    '''<summary>
    '''lblDashboardType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDashboardType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWelcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWelcome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlStatistics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStatistics As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProjects As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblProjectsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectsTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProjectsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectsCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSales As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSalesTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSalesTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSalesCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSalesCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlEarnings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEarnings As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblEarningsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEarningsTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEarnings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEarnings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlOpenRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOpenRequests As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblOpenRequestsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpenRequestsTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOpenRequestsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpenRequestsCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlMainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMainContent As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlMyProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMyProjects As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlProjectsHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProjectsHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMyProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMyProjects As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkViewProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkViewProjects As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''pnlProjectList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProjectList As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlProject1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProject1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblProject1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProject1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProject1Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProject1Status As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlProject2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProject2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblProject2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProject2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProject2Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProject2Status As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlProject3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProject3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblProject3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProject3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProject3Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProject3Status As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkAddProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddProject As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''pnlRecentSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRecentSales As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlSalesHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSalesHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblRecentSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecentSales As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkViewSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkViewSales As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''pnlSalesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSalesList As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlSale1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSale1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSale1Product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSale1Product As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSale1Price control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSale1Price As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSale1Details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSale1Details As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlSale2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSale2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSale2Product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSale2Product As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSale2Price control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSale2Price As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSale2Details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSale2Details As Global.System.Web.UI.WebControls.Label
End Class
