<%@ Page Title="Explore Projects" Language="VB" MasterPageFile="~/Masters/Site.Master" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <main class="py-14">
        <div class="flex items-end justify-between border-b border-slate-200 pb-9">
            <div><p class="text-sm font-semibold text-blue-600">MARKETPLACE</p><h1 class="mt-2 text-4xl font-bold tracking-tight text-slate-950">Explore projects</h1><p class="mt-3 text-slate-600">Ready-to-use projects created by the community.</p></div>
            <form class="flex w-[390px] items-center rounded-xl border border-slate-300 bg-white px-3 shadow-sm"><input class="w-full border-0 px-2 py-3 text-sm outline-none" type="search" placeholder="Search projects" /><button class="text-sm font-semibold text-blue-600" type="submit">Search</button></form>
        </div>
        <div class="mt-8 grid grid-cols-[240px_1fr] gap-10">
            <aside class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 class="font-bold text-slate-950">Filters</h2><div class="mt-6 border-t border-slate-100 pt-5"><p class="text-sm font-semibold">Category</p><div class="mt-3 space-y-3 text-sm text-slate-600"><label class="flex gap-2"><input type="checkbox" /> Web</label><label class="flex gap-2"><input type="checkbox" /> App</label><label class="flex gap-2"><input type="checkbox" /> Python</label><label class="flex gap-2"><input type="checkbox" /> AI / ML</label></div></div><div class="mt-6 border-t border-slate-100 pt-5"><p class="text-sm font-semibold">Price range</p><div class="mt-3 space-y-3 text-sm text-slate-600"><label class="flex gap-2"><input type="checkbox" /> Free</label><label class="flex gap-2"><input type="checkbox" /> Paid</label><label class="flex gap-2"><input type="checkbox" /> Under ₹500</label></div></div><button class="mt-7 w-full rounded-lg border border-slate-300 py-2.5 text-sm font-semibold text-slate-700">Clear filters</button></aside>
            <section><div id="categories" class="flex items-center justify-between"><p class="text-sm text-slate-500">Showing 12 projects</p><select class="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-700"><option>Sort by: Popular</option><option>Newest</option><option>Price: Low to high</option></select></div><div class="mt-5 grid grid-cols-3 gap-5">
                <article class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="aspect-[16/9] bg-gradient-to-br from-violet-500 via-blue-500 to-cyan-400"></div><div class="p-5"><a class="font-bold text-slate-950 hover:text-blue-600" href="<%= ResolveUrl("~/Pages/public/ProjectDetails.aspx") %>">Smart study planner</a><p class="mt-2 text-sm leading-6 text-slate-600">AI-powered planning for students and teams.</p><div class="mt-4 flex justify-between text-sm"><span class="text-amber-500">★ 3.7</span><strong>₹499</strong></div></div></article>
                <article class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="aspect-[16/9] bg-gradient-to-br from-emerald-500 via-teal-500 to-cyan-500"></div><div class="p-5"><a class="font-bold text-slate-950 hover:text-blue-600" href="<%= ResolveUrl("~/Pages/public/ProjectDetails.aspx") %>">Creator portfolio kit</a><p class="mt-2 text-sm leading-6 text-slate-600">A clean portfolio template for creators.</p><div class="mt-4 flex justify-between text-sm"><span class="text-amber-500">★ 4.2</span><strong>₹399</strong></div></div></article>
                <article class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="aspect-[16/9] bg-gradient-to-br from-orange-400 via-rose-500 to-fuchsia-600"></div><div class="p-5"><a class="font-bold text-slate-950 hover:text-blue-600" href="<%= ResolveUrl("~/Pages/public/ProjectDetails.aspx") %>">Expense tracker</a><p class="mt-2 text-sm leading-6 text-slate-600">Simple finances with useful insights.</p><div class="mt-4 flex justify-between text-sm"><span class="text-amber-500">★ 4.5</span><strong>₹299</strong></div></div></article>
                <article class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="aspect-[16/9] bg-gradient-to-br from-slate-700 via-slate-600 to-sky-700"></div><div class="p-5"><a class="font-bold text-slate-950 hover:text-blue-600" href="<%= ResolveUrl("~/Pages/public/ProjectDetails.aspx") %>">Team task board</a><p class="mt-2 text-sm leading-6 text-slate-600">Manage work with a flexible Kanban flow.</p><div class="mt-4 flex justify-between text-sm"><span class="text-amber-500">★ 4.0</span><strong>₹599</strong></div></div></article>
                <article class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="aspect-[16/9] bg-gradient-to-br from-pink-500 via-rose-400 to-orange-300"></div><div class="p-5"><a class="font-bold text-slate-950 hover:text-blue-600" href="<%= ResolveUrl("~/Pages/public/ProjectDetails.aspx") %>">Recipe companion</a><p class="mt-2 text-sm leading-6 text-slate-600">Discover recipes and plan your weekly meals.</p><div class="mt-4 flex justify-between text-sm"><span class="text-amber-500">★ 4.4</span><strong>₹249</strong></div></div></article>
                <article class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="aspect-[16/9] bg-gradient-to-br from-indigo-600 via-purple-600 to-pink-500"></div><div class="p-5"><a class="font-bold text-slate-950 hover:text-blue-600" href="<%= ResolveUrl("~/Pages/public/ProjectDetails.aspx") %>">Learning dashboard</a><p class="mt-2 text-sm leading-6 text-slate-600">Track progress across all of your courses.</p><div class="mt-4 flex justify-between text-sm"><span class="text-amber-500">★ 4.1</span><strong>₹449</strong></div></div></article>
            </div></section>
        </div>
    </main>
</asp:Content>
