'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dashboard

    '''<summary>
    '''lblOverview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverview As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDashboardTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDashboardTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlStats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStats As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUsers As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblUsersTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsersTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUsersCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsersCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProjects As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblProjectsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectsTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProjectsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectsCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOrders As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblOrdersTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrdersTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOrdersCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrdersCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlPendingReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPendingReports As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPendingReportsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingReportsTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendingReportsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingReportsCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlDashboardContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDashboardContent As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlRecentActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRecentActivity As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlActivityHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlActivityHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblRecentActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecentActivity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkViewOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkViewOrders As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''pnlActivities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlActivities As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlActivity1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlActivity1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblActivity1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActivity1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblActivity1Time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActivity1Time As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlActivity2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlActivity2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblActivity2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActivity2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblActivity2Time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActivity2Time As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlActivity3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlActivity3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblActivity3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActivity3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblActivity3Time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActivity3Time As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlRequiresReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRequiresReview As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblReviewTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkViewReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkViewReports As Global.System.Web.UI.WebControls.HyperLink
End Class
