'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class EditUser

    Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtUsername As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtContact As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
End Class
