<%@ Page Title="Edit User" Language="vb" AutoEventWireup="false" MasterPageFile="~/Masters/Admin.Master" CodeBehind="EditUser.aspx.vb" Inherits="BuildMeAProject.EditUser" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel ID="pnlMain" runat="server" CssClass="mx-auto w-[760px]">
        <asp:HyperLink ID="lnkBack" runat="server" NavigateUrl="~/Pages/admin/Users.aspx" Text="&larr; Back to users" CssClass="text-sm font-semibold text-blue-600" />
        <asp:Label ID="lblPageType" runat="server" Text="ACCOUNT MANAGEMENT" CssClass="mt-7 block text-sm font-semibold text-blue-600" />
        <asp:Label ID="lblPageTitle" runat="server" Text="Edit user" CssClass="mt-2 block text-4xl font-bold" />
        <asp:Label ID="lblPageDescription" runat="server" Text="Update this user's account details and access status." CssClass="mt-3 block text-sm text-slate-500" />
        <asp:Panel ID="pnlForm" runat="server" CssClass="mt-8 rounded-2xl bg-white p-8 shadow-sm ring-1 ring-slate-200">
            <asp:ValidationSummary ID="vsEditUser" runat="server" ValidationGroup="EditUser" CssClass="mb-5 block rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700" />
            <asp:Panel ID="pnlFields" runat="server" CssClass="space-y-5">
                <asp:Panel ID="pnlName" runat="server"><asp:Label ID="lblName" runat="server" Text="Name" AssociatedControlID="txtName" CssClass="block text-sm font-semibold" /><asp:TextBox ID="txtName" runat="server" Placeholder="Enter the user's full name" CssClass="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" /><asp:RequiredFieldValidator ID="rfvName" runat="server" ControlToValidate="txtName" ValidationGroup="EditUser" Display="Dynamic" Text="Name is required." CssClass="mt-2 block text-sm text-rose-600" /></asp:Panel>
                <asp:Panel ID="pnlUsername" runat="server"><asp:Label ID="lblUsername" runat="server" Text="Username" AssociatedControlID="txtUsername" CssClass="block text-sm font-semibold" /><asp:TextBox ID="txtUsername" runat="server" Placeholder="Enter a username" CssClass="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" /><asp:RequiredFieldValidator ID="rfvUsername" runat="server" ControlToValidate="txtUsername" ValidationGroup="EditUser" Display="Dynamic" Text="Username is required." CssClass="mt-2 block text-sm text-rose-600" /></asp:Panel>
                <asp:Panel ID="pnlEmail" runat="server"><asp:Label ID="lblEmail" runat="server" Text="Email" AssociatedControlID="txtEmail" CssClass="block text-sm font-semibold" /><asp:TextBox ID="txtEmail" runat="server" TextMode="Email" Placeholder="name@example.com" CssClass="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" /><asp:RequiredFieldValidator ID="rfvEmail" runat="server" ControlToValidate="txtEmail" ValidationGroup="EditUser" Display="Dynamic" Text="Email is required." CssClass="mt-2 block text-sm text-rose-600" /><asp:RegularExpressionValidator ID="revEmail" runat="server" ControlToValidate="txtEmail" ValidationGroup="EditUser" Display="Dynamic" ValidationExpression="^[^@\s]+@[^@\s]+\.[^@\s]+$" Text="Enter a valid email address." CssClass="mt-2 block text-sm text-rose-600" /></asp:Panel>
                <asp:Panel ID="pnlContact" runat="server"><asp:Label ID="lblContact" runat="server" Text="Contact no." AssociatedControlID="txtContact" CssClass="block text-sm font-semibold" /><asp:TextBox ID="txtContact" runat="server" TextMode="Phone" MaxLength="10" Placeholder="9876543210" CssClass="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" /><asp:RequiredFieldValidator ID="rfvContact" runat="server" ControlToValidate="txtContact" ValidationGroup="EditUser" Display="Dynamic" Text="Contact number is required." CssClass="mt-2 block text-sm text-rose-600" /><asp:RegularExpressionValidator ID="revContact" runat="server" ControlToValidate="txtContact" ValidationGroup="EditUser" Display="Dynamic" ValidationExpression="^[0-9]{10}$" Text="Contact number must contain exactly 10 digits." CssClass="mt-2 block text-sm text-rose-600" /></asp:Panel>
                <asp:Panel ID="pnlStatus" runat="server"><asp:Label ID="lblStatus" runat="server" Text="Status" AssociatedControlID="ddlStatus" CssClass="block text-sm font-semibold" /><asp:DropDownList ID="ddlStatus" runat="server" CssClass="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3"><asp:ListItem Text="ACTIVE" Value="ACTIVE" /><asp:ListItem Text="BANNED" Value="BANNED" /></asp:DropDownList></asp:Panel>
                <asp:Label ID="lblMessage" runat="server" CssClass="block text-sm font-medium text-rose-600" />
                <asp:Panel ID="pnlActions" runat="server" CssClass="flex items-center gap-3 pt-2"><asp:Button ID="btnSaveUser" runat="server" Text="Save changes" ValidationGroup="EditUser" OnClick="btnSaveUser_Click" CssClass="rounded-xl bg-blue-600 px-6 py-3 text-sm font-semibold text-white hover:bg-blue-700" /><asp:HyperLink ID="lnkCancel" runat="server" Text="Cancel" NavigateUrl="~/Pages/admin/Users.aspx" CssClass="rounded-xl border border-slate-300 px-6 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50" /></asp:Panel>
            </asp:Panel>
        </asp:Panel>
    </asp:Panel>
</asp:Content>
