'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dashboard2

    '''<summary>
    '''pnlMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMain As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDashboardType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDashboardType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''WelcomeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WelcomeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlStatistics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStatistics As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlPurchases control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPurchases As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPurchasesTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPurchasesTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPurchasesCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPurchasesCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRequests As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblRequestsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestsTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRequestsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestsCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlPitches control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPitches As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPitchesTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPitchesTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPitchesCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPitchesCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMessages As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMessagesTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessagesTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMessagesCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessagesCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlDashboardContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDashboardContent As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlRecentlyViewed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRecentlyViewed As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlRecentlyViewedHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRecentlyViewedHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblRecentlyViewed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecentlyViewed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkExploreProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExploreProjects As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''pnlProjectCards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProjectCards As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlProject1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProject1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlProject1Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProject1Image As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlProject1Details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProject1Details As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblProject1Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProject1Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProject1Tech control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProject1Tech As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProject1Price control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProject1Price As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlProject2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProject2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlProject2Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProject2Image As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlProject2Details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProject2Details As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblProject2Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProject2Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProject2Tech control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProject2Tech As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProject2Price control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProject2Price As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlQuickAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlQuickAction As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblQuickActionTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuickActionTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProjectIdea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectIdea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQuickActionDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuickActionDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkCreateRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCreateRequest As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lnkViewRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkViewRequests As Global.System.Web.UI.WebControls.HyperLink
End Class
